-- 코드를 입력하세요
SELECT YEAR(s.SALES_DATE) AS YEAR,
    MONTH(s.SALES_DATE) AS MONTH,
    i.GENDER,
    COUNT(DISTINCT i.USER_ID) AS USERS
from USER_INFO i 
join ONLINE_SALE s
on i.USER_ID = s.USER_ID
WHERE i.GENDER IS NOT NULL
group by YEAR(s.SALES_DATE),
    MONTH(s.SALES_DATE),
    i.GENDER
order by YEAR(s.SALES_DATE),
    MONTH(s.SALES_DATE),
    i.GENDER;